force-app/main/default/objects/Opportunity_Task__c/Opportunity_Task__c.object-meta.xml
<CustomObject>
    <label>Opportunity Task</label>
    <nameField>
        <label>Opportunity Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oportunity Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Task__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oportunity_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Task__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Oportunity Tasks</relationshipLabel>
    <relationshipName>Oportunity_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TaskSequenceController.cls
public with sharing class TaskSequenceController {
    @AuraEnabled(cacheable=true)
    public static List<Opportunity_Task__c> getOpportunityTasks(Id opportunityId) {
        if (String.isBlank(opportunityId)) {
            return new List<Opportunity_Task__c>();
        }
        return [
            SELECT Id, Task_Name__c, Status__c, Order__c, Due_Date__c,Assigned_To__r.Name
                FROM Opportunity_Task__c
                WHERE Opportunity__c = :opportunityId
                ORDER BY Order__c ASC
        ];
    }
    @AuraEnabled
    public static void updateTasks(List<Opportunity_Task__c> tasks) {
        if (tasks == null || tasks.isEmpty()) {
            throw new AuraHandledException('No valid data received.');
        }
        for (Opportunity_Task__c task : tasks) {
            if (task.Id == null) {
                throw new AuraHandledException('Each task must have an Id.');
            }
        }
        update tasks;
    }

}